version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - dsb-excel-generator

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
